services:
  postgres:
    image: postgres:16-alpine
    container_name: graphql_blog_db
    environment:
      POSTGRES_DB: graphql_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: graphql_blog_app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: graphql_blog
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
